EBIBioStudies/ribs

src/main/java/uk/ac/ebi/biostudies/service/impl/MongoDBServiceImpl.java, src/main/resources/application.properties
Also fix mongo db startup check of partial update flag
=> [Delivers #176607517] Fix mongo logging

src/main/resources/collection-fields.json
(keeping backward compatibility for now)
=> [Fixes #176783146] Rename projects to collections

src/main/java/uk/ac/ebi/biostudies/config/IndexConfig.java, src/main/java/uk/ac/ebi/biostudies/config/IndexManager.java, src/main/java/uk/ac/ebi/biostudies/controller/Index.java, src/main/java/uk/ac/ebi/biostudies/service/PartialUpdateListener.java, src/main/resources/index.properties
Add property for sync command for index backup
=> [Delivers #176871382] Ignore MQ messages for deleted accessions

.gitignore, src/main/resources/static/error.html, src/main/webapp/WEB-INF/tags/generic.tag, src/main/webapp/css/detail.css, src/main/webapp/css/search.css, src/main/webapp/jsp/detail/main-file-table.hbs
Also fix fietable view in smaller screens
=> [Delivers #176922046] Bump webframework version

src/main/webapp/css/detail.css, src/main/webapp/js/detail/filetable.js, src/main/webapp/jsp/detail/main-file-table.hbs
=> Improving Aspera UI

src/main/webapp/css/theme-biostudies.css, src/main/webapp/js/common/highlight.js
Fix white footer for new theme
=> [Delivers #176959165] Fix highlighting

src/main/java/uk/ac/ebi/biostudies/config/AnnouncementConfig.java, src/main/java/uk/ac/ebi/biostudies/config/JawrConfig.java, src/main/java/uk/ac/ebi/biostudies/config/MvcConfig.java, src/main/resources/announcement.properties, src/main/webapp/WEB-INF/web.xml
Fixing announcement.properties
=> Enable javascript packaging in JAWR's Environment flags

src/main/resources/collection-fields.json, src/main/resources/static/error.html, src/main/webapp/WEB-INF/tags/generic.tag, src/main/webapp/css/detail.css, src/main/webapp/js/common/global/common.js
Fix Forgot password link
Update collection default
=> [Delivers #177245391] Sync BIA header

src/main/resources/normalised-text.properties, src/main/webapp/js/collection/detail/arrayexpress.js, src/main/webapp/js/detail/detailpage.js, src/main/webapp/js/detail/filetable.js, src/main/webapp/jsp/search/all-facets.hbs, src/main/webapp/jsp/search/facet-list.hbs
Enable SDRF viewer
Fix MINSEQE/MIAME score for smaller width browsers
Fix facet checkbox
Rename GXA/GXA-SC links
Fix file selection filter
=> [Delivers #177183728] Fix interface for AE submissions

src/main/webapp/js/detail/metadata.js
in case of multiple URL resolutions from identifiers.org
=> [Deliver #177189970] Prioritise EBI links 

src/main/java/uk/ac/ebi/biostudies/controller/Authentication.java
=> Fixing login redirect problem

src/main/java/uk/ac/ebi/biostudies/api/util/parser/TitleParser.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FileIndexServiceImpl.java, src/main/resources/application.properties, src/main/resources/collection-fields.json, src/main/webapp/css/search.css, src/test/java/uk/ac/ebi/biostudies/integration/IntegrationTestSuite.java
Fix title
Fix integration tests for windows
=> Fix filelist path

.dockerignore, .gitlab-ci.yml, Dockerfile, src/main/java/uk/ac/ebi/biostudies/service/impl/FileIndexServiceImpl.java
=> Hotfix 2021-04-01

src/main/webapp/WEB-INF/tags/generic.tag, src/main/webapp/css/detail.css, src/main/webapp/js/collection/detail/arrayexpress.js, src/main/webapp/js/detail/filetable.js, src/main/webapp/js/detail/metadata.js, src/main/webapp/jsp/detail/attributes.hbs, src/main/webapp/jsp/detail/section-table.hbs, src/main/webapp/jsp/detail/section.hbs, src/main/webapp/jsp/detail/study.hbs
Update title and description metadata
=> [Delivers #177742755] Render attribute:value pairs in a single line

src/main/webapp/css/detail.css, src/main/webapp/js/detail/metadata.js, src/main/webapp/jsp/detail/section-table.hbs
=> Hide empty columns

src/main/java/uk/ac/ebi/biostudies/service/impl/FileIndexServiceImpl.java, src/main/webapp/css/detail.css, src/main/webapp/css/jquery.dataTables.css
Fix file table indexing
Fix table border colour
=> [Delivers #177851373] Fix spacing

src/main/java/uk/ac/ebi/biostudies/service/impl/ZipDownloadServiceImpl.java, src/main/webapp/css/detail.css, src/main/webapp/js/collection/detail/arrayexpress.js, src/main/webapp/js/detail/helpers.js, src/main/webapp/jsp/detail/attributes.hbs, src/main/webapp/jsp/detail/publication.hbs, src/main/webapp/jsp/detail/section-table.hbs, src/main/webapp/jsp/detail/section.hbs, src/main/webapp/jsp/detail/study.hbs
=> [Delivers #177873124] Allow duplicate entries is zip

src/main/java/uk/ac/ebi/biostudies/service/impl/SearchServiceImpl.java, src/main/webapp/js/search/helpers.js
=> Hotfix 2021-05-05

src/main/java/uk/ac/ebi/biostudies/schedule/jobs/UpdateOntologyJob.java
=> Fix version checking code for EFO update

src/main/java/uk/ac/ebi/biostudies/api/util/parser/TitleParser.java, src/main/java/uk/ac/ebi/biostudies/controller/Authentication.java, src/main/java/uk/ac/ebi/biostudies/service/TextService.java, src/main/java/uk/ac/ebi/biostudies/service/impl/IndexServiceImpl.java, src/main/webapp/js/detail/helpers.js, src/main/webapp/js/detail/metadata.js
Fix text normalisation to use only normalised-text.properties
Allow rendering of older submissions which are in json array format
=> [Delivers #178028147] Fix error on logging out twice

src/main/webapp/js/collection/detail/arrayexpress.js, src/main/webapp/js/common/global/common.js
Remove extra files link from AE submissions
=> [Delivers #178271181] Remove extra browse menu on BioImages

.gitignore, src/main/webapp/js/detail/filetable.js, src/main/webapp/js/detail/metadata.js
on fullscreen expansion as well
=> [Delivers #177923733] apply this to all tables

src/main/java/uk/ac/ebi/biostudies/service/impl/FacetServiceImpl.java
=> Fix Confusion in Facet Count

src/main/resources/collection-fields.json, src/main/webapp/js/detail/helpers.js
[Delivers #181139762] Fix link count
=> [Delivers #181140359] Show unattached orgs

src/main/java/uk/ac/ebi/biostudies/api/util/parser/DateParser.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FileDownloadServiceImpl.java, src/main/webapp/WEB-INF/tags/generic.tag, src/main/webapp/js/common/global/common.js, src/test/java/uk/ac/ebi/biostudies/integration/SearchTest.java
Remove AE header
Fix release date indexing
=> Release 2022.03.08

src/main/java/uk/ac/ebi/biostudies/service/impl/FilePaginationServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/SearchServiceImpl.java, src/main/webapp/js/detail/filetable.js, src/main/webapp/jsp/detail/study.hbs
[Fixes #181638304] Use the release date in the DB if the pagetab one is null
=> [Fixes #181637828] Remove current study from similar list

pom.xml, src/main/java/net/jawr/web/autoconfigure/JawrAutoConfiguration.java, src/main/java/uk/ac/ebi/biostudies/BioStudiesUI.java, src/main/java/uk/ac/ebi/biostudies/api/util/BioStudiesQueryParser.java, src/main/java/uk/ac/ebi/biostudies/api/util/parser/ParserManager.java, src/main/java/uk/ac/ebi/biostudies/config/JawrConfig.java, src/main/java/uk/ac/ebi/biostudies/config/MvcConfig.java, src/main/java/uk/ac/ebi/biostudies/controller/CustomErrorController.java, src/main/java/uk/ac/ebi/biostudies/efo/EFOExpansionLookupIndex.java, src/main/java/uk/ac/ebi/biostudies/service/impl/IndexServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/QueryServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/SearchServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/efo/Ontology.java
=> Release 2022.04.14

pom.xml, src/main/java/uk/ac/ebi/biostudies/efo/EFOExpansionLookupIndex.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FileDownloadServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/IndexServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/QueryServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/efo/Ontology.java
=> Release 2022.04.19

src/main/webapp/js/common/global/common.js, src/main/webapp/js/search/facetrenderer.js
[Delivers #181833065] Remove collection facet
=> [Delivers #181835070] Remove search checkbox for AE

pom.xml, src/main/java/uk/ac/ebi/biostudies/api/util/BioStudiesQueryParser.java, src/main/java/uk/ac/ebi/biostudies/api/util/parser/AbstractParser.java, src/main/java/uk/ac/ebi/biostudies/api/util/parser/ParserManager.java, src/main/java/uk/ac/ebi/biostudies/config/IndexManager.java, src/main/java/uk/ac/ebi/biostudies/controller/FileDownload.java, src/main/java/uk/ac/ebi/biostudies/controller/Index.java, src/main/java/uk/ac/ebi/biostudies/service/FacetService.java, src/main/java/uk/ac/ebi/biostudies/service/IndexManagementService.java, src/main/java/uk/ac/ebi/biostudies/service/IndexService.java, src/main/java/uk/ac/ebi/biostudies/service/RabbitMQStompService.java, src/main/java/uk/ac/ebi/biostudies/service/StartupService.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FacetServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FileDownloadServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FireService.java, src/main/java/uk/ac/ebi/biostudies/service/impl/IndexManagementServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/IndexServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/QueryServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/SearchServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/ZipDownloadServiceImpl.java, src/main/webapp/WEB-INF/tags/generic.tag, src/main/webapp/js/detail/filetable.js
=> Release 2022.05.18

src/main/webapp/js/detail/filetable.js
=> Release 2022.05.19

src/main/webapp/help/arrayexpress-help.html
- Change to MAGE-TAB format description and addition of pdf for download
- Small style change
=> Addon to AE collection help page update

src/main/java/uk/ac/ebi/biostudies/controller/FileDownload.java, src/main/java/uk/ac/ebi/biostudies/service/impl/BatchDownloadScriptBuilder.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FileDownloadServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FilePaginationServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FireService.java, src/main/java/uk/ac/ebi/biostudies/service/impl/ZipDownloadServiceImpl.java, src/main/resources/batchdl/ftp-unix, src/main/resources/batchdl/ftp-windows, src/main/webapp/js/detail/filetable.js, src/main/webapp/jsp/detail/study.hbs
[Delivers #181568867] Remove .pagetab extension
[Delivers #182415421] Allow colons in links
=> Release 2022.06.09

src/main/java/uk/ac/ebi/biostudies/service/impl/FileDownloadServiceImpl.java
Patch to serve .pagetab.tsv when .tsv is not found
=> Release 2022.06.15

src/main/webapp/js/detail/metadata.js
=> Resolving null exception(undefined) of title[0]

src/main/java/uk/ac/ebi/biostudies/api/util/Constants.java, src/main/java/uk/ac/ebi/biostudies/config/IndexConfig.java, src/main/java/uk/ac/ebi/biostudies/config/IndexManager.java, src/main/java/uk/ac/ebi/biostudies/controller/Index.java, src/main/resources/index.properties
=> Implement index shipping in k8s

.gitlab-ci.yml, src/main/java/uk/ac/ebi/biostudies/service/RabbitMQStompService.java, src/main/webapp/js/detail/helpers.js
Fix to ignore empty attributes for links
=> Release 2022.07.25

.gitlab-ci.yml, src/main/java/uk/ac/ebi/biostudies/service/impl/FireService.java, src/main/webapp/js/detail/metadata.js
Limit docker image to master
Fix close button on expansion
=> Release 2022.08.16

src/main/java/uk/ac/ebi/biostudies/controller/FileDownload.java
=> submitting Allow unicode characters in download scripts

src/main/java/uk/ac/ebi/biostudies/api/util/Constants.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FileIndexServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/IndexServiceImpl.java
S-BIAD2 had a huge library file which take hours for being parsed by a single thread therefore library parsing changed to multithread
[#183262658]
=> Enabling search on file attributes

src/main/webapp/js/detail/filetable.js, src/main/webapp/js/detail/helpers.js
This is Aybek problem with S-BIAD25
=> ui-js-ifcond-undefined-exception

src/main/webapp/js/common/global/common.js
REMBI template is not yet ready, so comment out menu item until it is ready
=> Comment out REMBI menu item when handling BioImages

src/main/java/uk/ac/ebi/biostudies/api/util/StudyUtils.java, src/main/java/uk/ac/ebi/biostudies/controller/FileDownload.java, src/main/java/uk/ac/ebi/biostudies/controller/Thumbnail.java
=> Fix thumbnails for fire files with space

src/main/webapp/js/detail/helpers.js, src/main/webapp/jsp/detail/similar-studies.hbs
Serve arrays from /arrays URLs
[#183326660]
=> Amending similar studies table

src/main/java/uk/ac/ebi/biostudies/controller/FileDownload.java, src/main/webapp/help/help.html, src/main/webapp/js/detail/filetable.js, src/main/webapp/js/detail/metadata.js, src/main/webapp/js/help/help.js, src/main/webapp/jsp/detail/main-file-table.hbs, src/main/webapp/jsp/detail/study.hbs, src/main/webapp/jsp/files.jsp
[Delivers  #183534504, #183735622]
=> Limit downloads to 1000 and fix ftp help

src/main/webapp/js/common/global/common.js
Reverts EBIBioStudies/ribs#172
=> Revert "Comment out REMBI menu item when handling BioImages" - We are now ready to deploy REMBI

src/main/webapp/js/common/global/common.js
Needed to make some more minor updates to keep menus in UI concurrent with REMBI menu of BioImage Archive
=> Update REMBI menu items

src/main/java/uk/ac/ebi/biostudies/file/download/FIREDownloadFile.java, src/main/webapp/js/detail/filetable.js
=> Fixing Show folder size for FIRE downloads and its zip download problem

src/main/java/uk/ac/ebi/biostudies/config/SpringSecurityConfig.java, src/main/java/uk/ac/ebi/biostudies/controller/FileDownload.java, src/main/webapp/js/detail/filetable.js, src/main/webapp/jsp/detail/main-file-table.hbs
Hide FTP/Aspera downloads for private submissions
=> [Delivers #184405212] Fix Aspera connect control

ci/deployment.tmpl, src/main/webapp/js/detail/helpers.js
Decrease readiness probe period
=> [Delivers #184251205] Allow multiline attributes

src/main/java/uk/ac/ebi/biostudies/service/impl/FireService.java, src/main/webapp/help/help.html, src/main/webapp/js/help/help.js
=> [Delivers #185147397] Add globus help

src/main/webapp/js/common/global/common.js, src/main/webapp/js/detail/metadata.js
[Delivers #185232925] Update OLS link
=> [Delivers #185255990] Fix link redirect on incorrect collection in URL

src/main/java/uk/ac/ebi/biostudies/config/FireConfig.java, src/main/java/uk/ac/ebi/biostudies/service/file/filter/FtpRedirectFilter.java, src/main/java/uk/ac/ebi/biostudies/service/impl/FileDownloadServiceImpl.java, src/main/resources/fire.properties, src/main/webapp/js/detail/utils.js
=> Create a flag to make customizable ftp redirecting

src/main/webapp/help/arrayexpress-help.html
Added two new codes for accessions.
CURD
ENAD
=> Updated arrayexpress help page with new accession codes.

src/main/webapp/js/detail/helpers.js, src/main/webapp/jsp/detail/study.hbs
=> Add 'creator' and 'licence' schema.org metadata

src/main/resources/external-services.properties, src/main/webapp/WEB-INF/tags/generic.tag
=> Remove Google Analytics code

src/main/webapp/js/common/global/common.js
The BIA website has launched a 'Gallaries' section as well as updated its policies and restructured some parts of its top-level menu. This commit syncs these changes into the BioStudies version of the BIA menu.
=> Finishes [#186249588 ] Update BIA menu with galleries and policies items

src/main/java/uk/ac/ebi/biostudies/config/IndexConfig.java, src/main/java/uk/ac/ebi/biostudies/config/IndexManager.java, src/main/java/uk/ac/ebi/biostudies/controller/Index.java, src/main/java/uk/ac/ebi/biostudies/controller/Study.java, src/main/java/uk/ac/ebi/biostudies/efo/index/EFOManager.java, src/main/java/uk/ac/ebi/biostudies/service/IndexService.java, src/main/java/uk/ac/ebi/biostudies/service/SearchService.java, src/main/java/uk/ac/ebi/biostudies/service/TextMiningLinkUpdater.java, src/main/java/uk/ac/ebi/biostudies/service/impl/IndexServiceImpl.java, src/main/java/uk/ac/ebi/biostudies/service/impl/SearchServiceImpl.java, src/main/resources/index.properties
=> Explore storing pagetab json in a Lucene index

src/main/webapp/js/common/global/common.js
Add MIFA, annotation help and other items to BIA menu and change top level name of menu from 'REMBI' to 'Metadata'
=> [Finishes #187131488] Sync Biostudies UI to reflect updates to BIA menu

src/main/webapp/jsp/submit.jsp
https://www.pivotaltracker.com/story/show/188311113
Update DOIs related information in the submit help page
=> Pivotal ID # 188311113: Crossref "Contributor" Element Registration

src/main/resources/collection-fields.json
Hello,
I have tried to add a few of the prioritised facets for the BioModels collection. Can you guys review and merge it if it looks good?
=> Customise the search facets for BioModels collection

src/main/resources/collection-fields.json
The titles should be exact with the names.
=> Correct the field names

pom.xml, src/main/java/uk/ac/ebi/biostudies/config/SpringSecurityConfig.java, src/main/java/uk/ac/ebi/biostudies/config/XSSFilter.java
- Reject requests with XSS attempts in the URL path
=> Address XSS vulnerability

src/main/webapp/jsp/arrayexpress.jsp
- Update link Find out more about the Functional Genomics group to point to the functional genomics web
=> Update ArrayExpress landing page with new team link
